### PR TITLE
[EBE-3880] Error shown in Jenkins logs: Slaves without instance not being recycled

### PR DESCRIPTION
**Pull request by gsanchezu**
Remove timedOut submitted slave requests.

@oserna3 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.50 and Jenkins instance at https://10.0.49.51

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/411/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.50 and Jenkins instance at https://10.0.49.51

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/413/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please again

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.50 and Jenkins instance at https://10.0.49.51

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/415/ for more details.

**Comment by gsanchezu** [comment]
@oserna3, the test is failing because of another fix that has been merged in a parallel PR, so this one can be reviewed! ACK? 👍?

**Comment by oserna3** [comment]
Finally let's get rid of the trace: "thousands minutes out of sync ...", cool!! ACK

**Comment by gsanchezu** [comment]
Jenkins, test this please again

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.50 and Jenkins instance at https://10.0.49.51

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/416/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please again 2

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.50 and Jenkins instance at https://10.0.49.51

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/417/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please again 3

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.50 and Jenkins instance at https://10.0.49.51

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/418/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please again 4

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.50 and Jenkins instance at https://10.0.49.51

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/419/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-m8hfq1, https://ops.elasticbox.com/services/instances/i-h7ax9p

**Pull request merged**
