### PR TITLE
[EBE-3865] [Support #889] Jenkins plugin fails to provision a new instance 

### PR DESCRIPTION
**Pull request by gsanchezu**
Fix slave provision with instances without tags
Fix tag assigment to ElasticBox slaves

@oserna3 ?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/405/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/406/ for more details.

**Comment by gsanchezu** [comment]
Jenkins test this please, without a whitespace

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/407/ for more details.

**Comment by oserna3** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.149 and Jenkins instance at https://10.0.50.34

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/409/ for more details.

**Comment by oserna3** [comment]
ACK

**Comment by gsanchezu** [comment]
@osanjuan Merge, please?

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-mo7z4m, https://ops.elasticbox.com/services/instances/i-8xtntm, https://ops.elasticbox.com/services/instances/i-xylgxc

**Pull request merged**
