### PR TITLE
[EBE-3883] Fix Job ebx_jenkins_plugin_test_indigo (common.sh)

### PR DESCRIPTION
**Pull request by gsanchezu**
Fix polling to check when EBX appliance is back online

@oserna3 😉?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.9 and Jenkins instance at https://10.0.49.10

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/410/ for more details.

**Comment by oserna3** [comment]
I think that the version for the header elasticbox-release is still 4.0

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.9 and Jenkins instance at https://10.0.49.10

**Comment by gsanchezu** [comment]
Ok @oserna3 👌, version reverted to 4!

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/412/ for more details.

**Comment by gsanchezu** [comment]
@osanjuan, ↘️ ↙️ ?

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-d0jipz, https://ops.elasticbox.com/services/instances/i-v2xwbn

**Pull request merged**
