### PR TITLE
[EBE-3826] Fix VAR_FILE error in plugin tests

### PR DESCRIPTION
**Pull request by gsanchezu**
Several changes included in these commits:
- Fix VAR_FILE error in plugin tests
- Fix PR lifecycle trigger code and logs
- Fix ConcurrentModificationException
- Add guava 11 dependency no enable GitHub plugin upgrade (significant increase in packaged file)

### CODE REVIEW

**Comment by gsanchezu** [comment]
@oserna3, could you please review and ACK?

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/372/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, porfa please, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/373/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, porfa porfa please, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/374/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, porfa porfa porfa please, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/375/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, porfa porfa porfa porfa, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/376/ for more details.

**Comment by DiegoSanjuan** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/377/ for more details.

**Comment by DiegoSanjuan** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/378/ for more details.

**Comment by DiegoSanjuan** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/379/ for more details.

**Comment by DiegoSanjuan** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/380/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, porfa 5, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/381/ for more details.

**Comment by DiegoSanjuan** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by gsanchezu** [comment]
Jenkins, test this please, la refinitiva

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/382/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.54.38 and Jenkins instance at https://10.0.54.40

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/383/ for more details.

**Comment by oserna3** [comment]
ACK

**Comment by gsanchezu** [comment]
@osanjuan This PR can now be merged!

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-rx1t2x, https://ops.elasticbox.com/services/instances/i-6omr9v

**Pull request merged**
