### PR TITLE
[EBE-3620] Migrate the last jenkins job (regarding the jenkins plugin) ebx_jenkins_plugin_slave_tests from catapult to indigo

### PR DESCRIPTION
**Pull request by gsanchezu**
Fix slave and build step tests.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.49.128 and Jenkins instance at https://10.0.49.129

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/414/ for more details.

**Comment by gsanchezu** [comment]
@oserna3, 👍?

**Comment by oserna3** [comment]
ack

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-tvhq4i, https://ops.elasticbox.com/services/instances/i-xioowf

**Pull request merged**
