### PR TITLE
[EBE-3809] Fails to trigger new Pull Request Job with PR with more than one commit

### PR DESCRIPTION
**Pull request by gsanchezu**
Add logs to triggering process for GitHub Hooks
Fix triggering process when more than 1 sync event was received, that was not triggering new build.
@oserna3 ACKK??

### CODE REVIEW

**Comment by gsanchezu** [comment]
@DiegoSanjuan ACK?

**Comment by DiegoSanjuan** [comment]
ACK. Reviewed and confirmed that now it works as expected.

**Comment by gsanchezu** [comment]
Jenkins test this please

**Comment by gsanchezu** [comment]
Jenkins test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/368/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, porfa plis, test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/369/ for more details.

**Comment by osanjuan** [comment]
@gsanchezu are you fixing the test?

**Comment by gsanchezu** [comment]
No, the ones that I'm fixing are from the new plugin, but there is also a
task to fix the old plugin tests: EBE-3826
https://elasticbox.atlassian.net/browse/EBE-3826.

Salud2 / Best regards,
Guillermo Sánchez Uríen
Software Engineer

Phone: +34 636 027 064

**Comment by gsanchezu** [comment]
Superseded by:  [EBE-3826] Fix VAR_FILE error in plugin tests #3 - Commit changes already included there

**Pull request closed without merging**
