### PR TITLE
Add logs to issue comment PR trigger

### PR DESCRIPTION
**Pull request by gsanchezu**
@oserna3 ACK?

### CODE REVIEW

**Comment by oserna3** [comment]
it wouldn't be great if we put more line break between logic blocks, ;-). Anyway ACK for me

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/387/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please again

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/388/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/389/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please again 2

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/390/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please again 3

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.34 and Jenkins instance at https://10.0.48.20

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/391/ for more details.

**Comment by oserna3** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/394/ for more details.

**Comment by oserna3** [comment]
Jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/395/ for more details.

**Comment by oserna3** [comment]
Jenkins test this, please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.34 and Jenkins instance at https://10.0.48.84

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/396/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.34 and Jenkins instance at https://10.0.48.84

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/397/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/398/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.34 and Jenkins instance at https://

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/400/ for more details.

**Comment by oserna3** [comment]
Jenkins test this, please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.34 and Jenkins instance at https://

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/402/ for more details.

**Comment by oserna3** [comment]
Jenkins test this, please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/403/ for more details.

**Comment by oserna3** [comment]
Jenkins test this, please

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticBox instance is available at https://10.0.48.34 and Jenkins instance at https://10.0.48.162

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/404/ for more details.

**Comment by oserna3** [comment]
ACK...great!!

**Comment by gsanchezu** [comment]
@osanjuan Could you please merge? We are going to release

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-z5zjpe, https://ops.elasticbox.com/services/instances/i-61tzab

**Pull request merged**
