### PR TITLE
[Do not merge yet] PR lifecycle test additional logging

### PR DESCRIPTION
**Pull request by gsanchezu**
@oserna3 This is the PR for testing the PR lifecycle

### CODE REVIEW

**Comment by DiegoSanjuan** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/370/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin/371/ for more details.

**Comment by gsanchezu** [comment]
Superseded by: #3 [EBE-3826] Fix VAR_FILE error in plugin tests - All commits already included there

**Pull request closed without merging**
